### ISSUE TITLE
Seems like gtk application workaround is not needed anymore

### ISSUE THREAD

**Issue by itsdonnix** [vgtk/vgtk3#29]
I think its work now @trufae => https://github.com/donnisnoni/vgtk3/commit/5a08395b1ffe7d7e8a0d7f5179bb8d4580513240

**Comment by trufae** [comment]
Oh! I will have a look at this! Thanks for the heads up!

**Comment by itsdonnix** [comment]
Your welcome! BTW Are you have planning to using vgtk on your next project?

**Comment by itsdonnix** [comment]
Fixed by https://github.com/vgtk/vgtk3/pull/30/commits/bf0ca1e287d96495c87e67fecfd63702d1ca6a3e
