### ISSUE TITLE
2 tests failing  when using homebrew

### ISSUE THREAD

**Issue by rcqls** [vgtk/vgtk3#34]
Hi, thanks for this nice project. 

Just to let you know that I have proposed a minimal PR in the `vlang/v` repo to fix `pkgconfig` that was unable to resolve the file object-2.0.pc (notably the unusual line: `Requires.private: /usr/local/opt/libffi/lib/pkgconfig/libffi.pc >=  3.0.0`) in my homebrew installation for macOS. Also, as a complement, `export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"`was needed.

**Comment by itsdonnix** [comment]
Hi... So glad you like this  project man!
I think your PR is already merged. I don't have mac machine, can you help do this instead?

**Comment by rcqls** [comment]
@donnisnoni What do you want me to do? Everything is fine now and I can now play with the examples without any errors.

**Comment by itsdonnix** [comment]
Ahh... my bad,, missunderstanding... 
I think this one is needed to insert inside vgtk 3
```
as a complement, export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig" was needed.
```

**Comment by itsdonnix** [comment]
Thanks man!

**Comment by itsdonnix** [comment]
BTW checkout https://github.com/vgtk/g-gen... WIP tool to generate wrapper for vgtk3. So far I think as V grows,, there are so many changes on it so i'm not really working on it. Instead we do a manual wrapper

**Comment by itsdonnix** [comment]
@zenith391 Can you close this?

**Comment by rcqls** [comment]
Hi @donnisnoni I am not @zenith391  but I can close this issue ....

**Comment by itsdonnix** [comment]
ahhh... i forgot lol @rcqls
