### ISSUE TITLE
need to call window.add() once to run the program

### ISSUE THREAD

**Issue by dhonx** [vgtk/vgtk3#7]
## What did you do?

Not works
```v
import gtk

fn main() {
    window := gtk.new_window()
    window.set_default_size(100, 100)
    window.set_title('gtk window')
    window.show()
    gtk.main()
}
```

works:
```v
import gtk

fn main() {
    window := gtk.new_window()
    btn := gtk.new_button('button')
    window.set_default_size(100, 100)
    window.set_title('gtk window')
    window.add(btn)
    window.show()
    gtk.main()
}
```

### What did you expect to see?
The window will appear

### What did you see instead?
https://pastebin.com/eNqHwLE0

According to @spytheman, this bug is related to the Interface bug on V

**Comment by zenith391** [comment]
True bug, however it can't be fixed by us as it is a bug internal to the V language.

**Comment by donnisnoni95** [comment]
@zenith391 Yeah... so we close this...??

**Comment by spytheman** [comment]
Please, do not close this issue, at least not, until it is solved in the v's code generation of the inteface implementation (i.e. the *_name_table should be initialized even if there are no interface methods called at all). That will happen today/tomorrow tops.

**Comment by spytheman** [comment]
This is solved now. You can verify that it works now with latest v.
